<a href="https://colab.research.google.com/github/swaruchi58/Basics-of-Python/blob/main/Assignment_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Name : Swaruchi Chitrangad Mhatre

#Assignment - I

#Problem Statement 1: Write a Python program to multiply a M × N matrix by N × A matrix and create a real matrix product.

In [1]:
import numpy as np

In [2]:
a=np.random.random((5,3))
print("First array:")
print(a)

First array:
[[0.87538617 0.79833657 0.42391354]
 [0.66664392 0.67921876 0.87074497]
 [0.98865438 0.76820712 0.85033557]
 [0.72849167 0.55263395 0.63667118]
 [0.45398616 0.36885804 0.65928799]]


In [3]:
b=np.random.random((3,2))
print("Second array:")
print(b)

Second array:
[[0.80776545 0.75668994]
 [0.28426088 0.77874951]
 [0.25566091 0.11615879]]


In [4]:
c=np.dot(a,b)
print("Dot product of two arrays:")
print(c)

Dot product of two arrays:
[[1.04242067 1.3333414 ]
 [0.95418269 1.1345287 ]
 [1.23436963 1.44511968]
 [0.90831454 1.05556069]
 [0.64012041 0.70735687]]


#Problem Statement 2: Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only.

In [5]:
x=np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype=np.str)
print("\nOriginal Array:")
print(x)


Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5']


<ipython-input-5-a0b59a76bb4c>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x=np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'], dtype=np.str)


In [6]:
r1 = np.char.isdigit(x)
r2 = np.char.islower(x)
r3 = np.char.isupper(x)

print("Digits only =", r1)
print("Lower cases only =", r2)
print("Upper cases only =", r3)

Digits only = [False False False False False  True]
Lower cases only = [False False False False  True False]
Upper cases only = [False  True  True False False False]


#Problem Statement 3: Write a program thatreads two space-separated positive integers 2 and 3 as input and perform the following tasks:

1.Create a list (lst1) starting at one (1) with 16 elements at a step of 2

In [7]:
lst1=list(range(1,32,2))
lst1

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]

2.Create a list (lst2) starting at one (1) with 16 elements at a step of 3

In [8]:
lst2=list(range(1,47,3))
lst2

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46]

3.Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively

In [9]:
np1=np.array(lst1)
np1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [10]:
np2=np.array(lst2)
np2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46])

4.Reshape both the NumPy arrays to (4,4)

In [11]:
X=np1.reshape(4,4)
X

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

In [12]:
Y=np2.reshape(4,4)
Y

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

5.Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -np2)

In [13]:
np3=(np1-np2)
np3

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12,
       -13, -14, -15])

6.Print all the elements of np3 in a single dimension list like the format as shown below:a. [n0 n1 n2 n3 n4 n5 n6 n7 n8]

In [14]:
print(np3)

[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15]


#Problem Statement 4: Write a Python program that takes two integer-NumPy arrays, P and Q of shape [3∗3] and performt he following task:

Print the element-wise difference of the matrix 푃and푄(푃−푄).

In [15]:
P=np.array([23,56,87,3,6,96,4,6,78])
Q=np.array([12,34,54,7,2,54,6,2,78])

In [16]:
P-Q

array([11, 22, 33, -4,  4, 42, -2,  4,  0])

In [17]:
z=(P-Q).reshape(3,3)
z

array([[11, 22, 33],
       [-4,  4, 42],
       [-2,  4,  0]])

**OR**

In [18]:
p=P.reshape(3,3)
p

array([[23, 56, 87],
       [ 3,  6, 96],
       [ 4,  6, 78]])

In [19]:
q=Q.reshape(3,3)
q

array([[12, 34, 54],
       [ 7,  2, 54],
       [ 6,  2, 78]])

In [20]:
z=p-q
z

array([[11, 22, 33],
       [-4,  4, 42],
       [-2,  4,  0]])